{% set version = "1.3.5" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-syncsa
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/SYNCSA_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/SYNCSA/SYNCSA_{{ version }}.tar.gz
  sha256: a2717d0b8897e0b139443dcfd09c1d43f42c6634876dec3a2316815895f9ff4d

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-fd
    - r-rcpparmadillo
    - r-permute
    - r-vegan
  run:
    - r-base
    - r-fd
    - r-rcpparmadillo
    - r-permute
    - r-vegan

test:
  commands:
    - $R -e "library('SYNCSA')"           # [not win]
    - "\"%R%\" -e \"library('SYNCSA')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=SYNCSA
  license: GPL-2.0-only
  summary: Analysis of metacommunities based on functional traits and phylogeny of the community components. The functions that are offered here implement for the R environment methods that have been available in the SYNCSA application written in C++ (by Valerio Pillar, available at <http://ecoqua.ecologia.ufrgs.br/SYNCSA.html>).
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - clami66
